#!/usr/bin/env zsh

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME='robbyrussell'

plugins=()

source "$ZSH/oh-my-zsh.sh"

relative() {
  if [[ "$PWD" == "$SESSION_PATH" ]]; then
    echo ''
  elif [[ "$PWD" == "$SESSION_PATH"/* ]]; then
    echo " ${PWD#$SESSION_PATH/}"
  else
    echo ' ~'
  fi
}

PROMPT="%(?:%{$fg[white]%}%1{❯%}:%{$fg[red]%}%1{❯%})%{$fg_bold[cyan]%}\$(relative)%{$reset_color%} "
PROMPT+='$(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}%1{✗%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
