[env]
TERM = "screen-256color"

[font]
size = 24.0

[window]
opacity = 0.9

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[cursor.style]
blinking = "Always"

[mouse]
hide_when_typing = true
