#!/usr/bin/env bash

all_packages=$@

if [[ $# -eq 0 ]]; then
    [[ $(ansible localhost -m setup -a 'filter=ansible_os_family') =~ ansible_os_family\":\ \"([^\"]+)\" ]] || exit 1
    all_packages="${BASH_REMATCH[1]}
    $(<"$HOME/.dotfiles/packages-common")
    $(<"$HOME/.dotfiles/packages-${BASH_REMATCH[1]}")"
fi

for place in "$HOME/personal/ansible-roles" "$HOME/.dotfiles"; do
    cd "$place" && ./install "$all_packages" || exit 1
done
