#!/usr/bin/env bash

if [ "$(git config core.sparseCheckout)" = 'true' ]; then
    git sparse-checkout add "$@" --skip-checks
fi

declare -a nap=()
declare -a seen=()

for package in "$@"; do
    if [[ " ${seen[*]} " =~ " $package " ]]; then
        continue
    fi

    seen+=("$package")
    if [ -d "$package" ]; then
        printf 'stow %s\n' "$package"
        stow --restow "$package"
    else
        nap+=("$package")
    fi
done

for package in "${nap[@]}"; do
    printf 'stow: %s is not a package\n' "$package"
done
