#!/usr/bin/env bash

declare -a nap=()
declare -a seen=()

for package in "$@"; do
    if [[ " ${seen[*]} " =~ " $package " ]]; then
        continue
    fi

    seen+=("$package")
    if [ -d "$package" ]; then
        printf 'unstow %s\n' "$package"
        stow --delete "$package"
    else
        nap+=("$package")
    fi
done

for package in "${nap[@]}"; do
    printf 'stow: %s is not a package\n' "$package"
done
