#!/usr/bin/env sh

spaces=$(yabai -m query --spaces)

yabai --restart-service

wait

echo "$spaces" | jq --compact-output '.[]' | while read -r space; do
    yabai -m space \
        "$(echo "$space" | jq -r '.index')" \
        --label "$(echo "$space" | jq -r '.label')" ||
        exit 1
done
