#!/bin/env bash

# Running this script with sudo works

PATH="$HOME/.local/scripts:$PATH"

dir="$HOME/mnt/android"

echo "Mounting Android device ..."
mkdir -p "$HOME/mnt" && sudo aft-mtp-mount "$dir" || exit 1
echo "Android device mounted successfully"

sources=(
    "$dir/Internal storage/DCIM/Camera"
    "$dir/Internal storage/DCIM/Camera/RAW"
    "$dir/Internal storage/DCIM/OpenCamera"
)

empty=true
empty_msg=

for source in "${sources[@]}"; do
    sudo find "$source" -type f \( -name '*.jpg' -o -name '*.mp4' \) | pictures-import "$HOME/Pictures/digikam"
    sudo find "$source" -type f -name '*.dng' | pictures-import "$HOME/Pictures/darktable"

    files=$(sudo ls -A "$source")
    [[ -n "$files" ]] && empty=false
    empty_msg+="Directory '$source' is $([[ -z "$files" ]] && echo 'empty' || echo 'not empty')\n"
done

printf "$empty_msg"
echo "Android device is $([[ "$empty" == true ]] && echo 'empty' || echo 'not empty')"

echo "Unmounting Android device ..."
sudo fusermount -u "$dir" || exit 1
echo "Android device unmounted successfully"
