#!/usr/bin/env bash

# Produces correctly cropped Instagram photos in the current working directory

if ! command -v magick &>/dev/null; then
    echo 'Error: ImageMagick is not installed.'
    exit 1
fi

if ! command -v exiv2 &>/dev/null; then
    echo 'Error: Exiv2 is not installed.'
    exit 1
fi

if ! command -v shasum &>/dev/null; then
    echo 'Error: shasum is not installed.'
    exit 1
fi

crop=$1
replace_files=$2
usage='Usage:

    instagram-resizer <crop> [replace]
'

case "$crop" in
square)
    width=1080
    height=$width
    ;;
landscape)
    width=1080
    height=566
    ;;
portrait)
    width=1080
    height=1350
    ;;
*)
    echo "Error: Instagram post crop can be square, landscape, or portrait:

square      1:1      1080x1080
landscape   1.91:1   1080x566
portrait    4:5      1080x1350

Width of 1080 pixels and aspect ratio between 1.91:1 and 4:5.

https://help.instagram.com/1631821640426723

https://www.adobe.com/express/discover/sizes/instagram

$usage"
    exit 1
    ;;
esac

border_color=#ffffff

min_border=$((7 * (width / 100)))

watermark() {
    local file_name=$1
    local file_name_sha1sum=("$(echo -n "${file_name%.*}" | shasum)")
    echo "@photatogo  $(date '+%Y%m')  ${file_name_sha1sum[0]:0:6}"
}

hex=${border_color#\#}
r=$((16#${hex:0:2}))
g=$((16#${hex:2:2}))
b=$((16#${hex:4:2}))
luminance=$(((r * 2126 + g * 7152 + b * 722) / 10000))
if [ "$luminance" -gt 128 ]; then
    watermark_color=#000000
else
    watermark_color=#ffffff
fi

case "$(uname -s)" in
Linux)
    watermark_font="$HOME/.local/share/fonts/UbuntuMonoNerdFontMono-Regular.ttf"
    ;;
Darwin)
    watermark_font="$HOME/Library/Fonts/UbuntuMonoNerdFontMono-Regular.ttf"
    ;;
*)
    echo 'Error: Operating system not supported (no font).'
    exit 1
    ;;
esac

while IFS= read -r source_file; do
    file_name=$(basename "$source_file")
    dest_file="./${file_name%.*}_$(echo "$crop" | tr '[a-z]' '[A-Z]').${file_name##*.}"

    if [ -e "$dest_file" ]; then
        if [ "$replace_files" == true ]; then
            source_mod_time=$(date -r "$source_file" +%Y%m%d%H%M%S)
            dest_mod_time=$(date -r "$dest_file" +%Y%m%d%H%M%S)

            if [ "$source_mod_time" -le "$dest_mod_time" ]; then
                echo "Info: Destination newer than source. Skipping $source_file"
                continue
            fi
        else
            echo "Error: File or directory already exists. $dest_file"
            echo "Hint: $usage"
            exit 1
        fi
    fi

    magick "$source_file" \
        -resize "$((width - min_border * 2))x$((height - min_border * 2))>" -background "$border_color" -gravity center -extent "${width}x${height}" -colorspace sRGB \
        -rotate 90 -gravity southwest -font "$watermark_font" -pointsize "$((width / 36))" -stroke "$watermark_color" -fill "$watermark_color" -strokewidth "$((width / 1080))" -annotate "+$((width / 108))+$((width / 108))" "$(watermark "$file_name")" -rotate 270 \
        "$dest_file" && exiv2 rm "$dest_file" || exit 1
done
