#!/usr/bin/env bash

sanitize_name() {
    echo "$1" | tr . _
}

case "$#" in
0)
    find_projects() {
        {
            declare -a args=()
            declare -a active_sessions=()
            while read session; do
                IFS=':' read -r _ session_attached session_path session_windows <<<"$session"

                args+=(-not -path "$session_path")

                session_item=
                if [ "$1" = inline-preview ]; then
                    session_item="${session_path}: ${session_windows}"
                else
                    session_item="$session_path"
                fi

                if [ "$session_attached" = 1 ]; then
                    active_sessions=("$session_item" "${active_sessions[@]}")
                else
                    echo "$session_item"
                fi
            done < <(
                tmux list-sessions -F '#{session_last_attached}:#{session_attached}:#{session_path}:#{T:tree_mode_format}' |
                    sort -rn 2>/dev/null
            )

            for active_session in "${active_sessions[@]}"; do
                echo "$active_session"
            done

            find "$HOME" "${HOME}/personal" "${HOME}/work" -mindepth 1 -maxdepth 1 -type d "${args[@]}"
        } | sed "s%^${HOME}/%%"
    }
    "$0" "$(
        if [[ "$(tmux display-message -p '#{window_width}')" -lt 120 ]]; then
            find_projects inline-preview | fzf-tmux --delimiter ':' \
                --nth '1' \
                --accept-nth '1' \
                --scheme path \
                --tiebreak 'begin,pathname,length' \
                -p 80%,90%
        else
            find_projects | fzf-tmux --scheme path \
                --tiebreak 'begin,pathname,length' \
                -p 80%,90% \
                --preview "
            PATH='$PATH'
            $(declare -f sanitize_name)
            tmux-tree \"\$(sanitize_name '{}' | cut -d ':' -f 1)\"
            "
        fi
    )"
    ;;
1)
    selected="$1"

    if [ -z "$selected" ]; then
        exit
    fi

    if [ ! -d "${HOME}/${selected}" ]; then
        exit 1
    fi

    session_name=$(sanitize_name "$selected")

    if ! tmux has-session -t "=${session_name}" 2>/dev/null; then
        case "$selected" in
        'personal' | 'work')
            tmux new-session -d -c "${HOME}/${selected}" -s "$session_name"
            ;;
        *)
            tmux new-session -d -c "${HOME}/${selected}" -s "$session_name" 'zsh -ic vim' \; \
                new-window -d -c "${HOME}/${selected}" -t "$session_name"
            ;;
        esac
    fi

    tmux switch-client -t "=$session_name"
    ;;
esac
