#!/usr/bin/env bash

while read s; do
    S=$(tmux ls -F '#{session_id}:#{session_name}: #{T:tree_mode_format}' | grep ^"$s:")
    session_info="${S##$s:}"
    session_name="$(echo "$session_info" | cut -d ':' -f 1)"
    if [[ "$1" == "$session_name" ]]; then
        echo -e "- \033[1;34m$session_info\033[0m"
    else
        echo -e "- $session_info"
    fi
    tmux lsw -t "$s" -F'#{window_id}' | while read -r w; do
        W=$(tmux lsw -t "$s" -F'#{window_id}#{T:tree_mode_format}' | grep ^"$w")
        echo "└─> ${W##$w}"
    done
done < <(
    tmux list-sessions -F '#{session_created} #{session_id}' |
        sort -rn |
        cut -d ' ' -f2- 2>/dev/null
)
