#!/usr/bin/env bash

PATH="$HOME/.local/scripts:$PATH"

selected=$(sed "${1}q;d" ~/.config/tmux/tmux-quick-menu | sed "s#~#$HOME#" | sed 's#/$##')

if [[ -d $selected ]]; then
    tmux-sessionizer "$selected"
fi
