#!/usr/bin/env bash

sanitize_name() {
    echo "$1" | tr . _
}

case "$#" in
0)
    "$0" "$(
        tmux_sessions=$(
            tmux list-sessions -F '#{session_last_attached} #{session_path}' |
                sort -rn |
                tail -n +2 |
                cut -d ' ' -f2- 2>/dev/null
        )

        {
            (test -n "$tmux_sessions" && echo "$tmux_sessions") &

            declare -a args=()
            while read s; do
                args+=('-not' '-path' "$s")
            done < <(echo "$tmux_sessions")

            wait

            find "$HOME" "$HOME/personal" "$HOME/work" -mindepth 1 -maxdepth 1 -type d "${args[@]}"
        } |
            sed "s%^$HOME/%%" |
            fzf-tmux -p 80%,80% --preview "PATH='$PATH'; $(declare -f sanitize_name); tmux-tree \"\$(sanitize_name {})\""
    )"
    ;;
1)
    selected="$1"

    if [ -z "$selected" ]; then
        exit
    fi

    if [ ! -d "$HOME/$selected" ]; then
        exit 1
    fi

    clean_name="$(sanitize_name "$selected")"

    if ! tmux has-session -t "=$clean_name" 2>/dev/null; then
        tmux new-session -ds "$clean_name" -c "$HOME/$selected"
    fi

    tmux switch-client -t "$clean_name"
    ;;
esac
