#!/usr/bin/env bash

while IFS=':' read -r _ session_name session_windows; do
    if [[ "$1" == "$session_name" ]]; then
        echo -e "- \033[1;34m${session_name}: ${session_windows}\033[0m"
    else
        echo -e "- ${session_name}: ${session_windows}"
    fi
    while IFS= read -r window_tree; do
        echo "└─> ${window_tree}"
    done < <(
        tmux list-windows -t "$session_name" -F '#{T:tree_mode_format}' 2>/dev/null
    )
done < <(
    tmux list-sessions -F '#{session_created}:#{session_name}:#{T:tree_mode_format}' |
        sort -n 2>/dev/null
)
