#!/usr/bin/env bash

selected=$(
find /System/Library/CoreServices /System/Applications /Applications \
    -mindepth 1 \
    -maxdepth 2 \
    -type d \
    -name '*.app' \
    -exec basename {} \; \
    | sed 's/\.app$//' \
    | ~/.local/scripts/dmenu-mac -i
)

if [[ -z $selected ]]
then
    # TODO: hide Xquartz
    exit
fi

case "$selected" in
    Firefox)
        firefox
        ;;
    *)
        open -a "$selected"
        ;;
esac

initial_space=$(yabai -m query --spaces --space | jq -r '.index')

timeout=10
interval=0.1
elapsed=0

while [[ $(yabai -m query --windows --window | jq -r '.app') != $selected ]]
do
    ((elapsed >= timeout)) && exit 1
    sleep $interval
    ((elapsed += interval))
done

yabai -m window --space "$initial_space" --focus
