#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# ```
# sudo sh -c 'echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai)) --load-sa" > /private/etc/sudoers.d/yabai'
# ```
#
# Scripting addition requres disable [SIP].
#
# [SIP]: github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
# [Apple Disable SIP]: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
#

# load scripting additions
yabai -m signal --add event=dock_did_restart action='sudo yabai --load-sa'
sudo yabai --load-sa

yabai -m rule --add app="^System Settings$" manage=off

yabai -m config                                 \
    layout                       bsp            \
    mouse_follows_focus          off            \
    window_shadow                off            \
    window_gap                   06             \
    focus_follows_mouse          off            \
    mouse_modifier               alt            \
                                                                                                   
# configure spaces
for i in {1..9}; do
    yabai -m space "$i" --label "space-${i}"
done
