#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# ```
# sudo sh -c 'echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai)) --load-sa" > /private/etc/sudoers.d/yabai'
# ```
#
# Scripting addition requres disable [SIP].
#
# [SIP]: github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
#

# load scripting additions
yabai -m signal --add event=dock_did_restart action='sudo yabai --load-sa'
sudo yabai --load-sa

yabai -m config                                 \
    layout                       bsp            \
    mouse_follows_mouse          on             \
    window_shadow                off            \
    window_gap                   06             \
    focus_follows_mouse          on             \
    mouse_modifier               alt            \
                                                                                                   
# configure spaces
for i in {1..9}; do
    yabai -m space $i --label space-$i
done
