#!/usr/bin/env sh

# reload with `yabai --restart-service`

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# sudo visudo -f /private/etc/sudoers.d/yabai
#
# and write the result from
#
# ```
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai)) --load-sa"
# ```
#
# requres disable SIP: github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
#

# load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
pass "$(whoami)" | head -n 1 | sudo --stdin yabai --load-sa

yabai -m config layout bsp
yabai -m config mouse_modifier alt # use mouse+alt to drag/resize windows
yabai -m config window_gap 2
yabai -m config window_shadow off
yabai -m config focus_follows_mouse on

# configure spaces
for i in {1..9}; do
    yabai -m space $i --label space-$i
done
