#!/usr/bin/env bash

username='nklkbdy9s6dkcu9ykob8oxzuh'
password=$(pass "personal/spotify.com/$username" | head -n 1)

args="--disable-audio-cache \
      --disable-credential-cache \
      --name "${USER}@${HOSTNAME}" \
      --device-type computer \
      --bitrate 320 \
      --username "$username" \
      --password "$password" \
      --format F32 \
      --initial-volume 100 \
      --disable-gapless"

librespot $args $@
