#!/usr/bin/env bash

librespot --cache "$HOME/.cache/librespot" \
    --enable-oauth \
    --disable-audio-cache \
    --name "${USER}@${HOSTNAME}" \
    --device-type computer \
    --bitrate 320 \
    --format F32 \
    --initial-volume 100 \
    --disable-gapless \
    "$@"
