#!/bin/env bash

set -euo pipefail

PATH="$HOME/.local/scripts:$PATH"

dir="$HOME/mnt/android"

echo "Mounting Android device ..."
mkdir -p "$dir" && sudo aft-mtp-mount "$dir"
echo "Android device mounted successfully"

sources=(
    "$dir/Internal storage/DCIM/Camera"
    "$dir/Internal storage/DCIM/Camera/RAW"
    "$dir/Internal storage/DCIM/OpenCamera"
)

empty=true
empty_msg=

for source in "${sources[@]}"; do
    sudo find "$source" -type f -name '*.dng' | pictures-import --dest "$HOME/Pictures/darktable" --remove
    sudo find "$source" -type f \( -name '*.jpg' -o -name '*.mp4' \) | pictures-import --dest "$HOME/Pictures/digikam" --remove

    files=$(sudo ls -A "$source")
    [[ -n "$files" ]] && empty=false
    empty_msg+="Directory '$source' is $([[ -z "$files" ]] && echo 'empty' || echo 'not empty')\n"
done

printf "$empty_msg"
echo "Android device is $([[ "$empty" == true ]] && echo 'empty' || echo 'not empty')"

echo "Unmounting Android device ..."
sudo fusermount -u "$dir"
echo "Android device unmounted successfully"
