#!/bin/env bash

PATH="$HOME/.local/scripts:$PATH"

device=$1
dir="$HOME/mnt/fuji-x-t5"

if [[ -b "$device" ]]; then
    echo "Mounting block device '$1' ..."
    sudo mount --mkdir "$device" "$dir" || exit 1
    echo "Device '$device' mounted successfully"
else
    echo "Error: $device is not a block device" && exit 1
fi

sources=(
    "$dir/dcim/100_fuji"
)

empty=true
empty_msg=

for source in "${sources[@]}"; do
    find "$source" -type f \( -name '*.JPG' -o -name '*.MOV' \) | pictures-import "$HOME/Pictures/digikam"
    find "$source" -type f -name '*.RAF' | pictures-import "$HOME/Pictures/darktable"

    files=$(ls -A "$source")
    [[ -n "$files" ]] && empty=false
    empty_msg+="Directory '$source' is $([[ -z "$files" ]] && echo 'empty' || echo 'not empty')\n"
done

printf "$empty_msg"
echo "Device '$device' is $([[ "$empty" == true ]] && echo 'empty' || echo 'not empty')"

echo "Unmounting block device '$device' ..."
sudo umount "$dir" || exit 1
echo "Device '$device' unmounted successfully"
