#!/bin/env bash

set -euo pipefail

PATH="$HOME/.local/scripts:$PATH"

device="$1"
dir="$HOME/mnt/sony-rx100"

if [[ -b "$device" ]]; then
    echo "Mounting block device '$1' ..."
    sudo mount --mkdir "$device" "$dir"
    echo "Device '$device' mounted successfully"
else
    echo "Error: $device is not a block device" && exit 1
fi

sources=(
    "$dir/DCIM/100MSDCF"
)

empty=true
empty_msg=

for source in "${sources[@]}"; do
    # NOTE: No remove option because this is a shared camera (and SD card)
    find "$source" -type f \( -name '*.JPG' -o -name '*.MOV' \) | pictures-import --dest "$HOME/Pictures/digikam"
    find "$source" -type f -name '*.ARW' | pictures-import --dest "$HOME/Pictures/darktable"

    files=$(ls -A "$source")
    [[ -n "$files" ]] && empty=false
    empty_msg+="Directory '$source' is $([[ -z "$files" ]] && echo 'empty' || echo 'not empty')\n"
done

printf "$empty_msg"
echo "Device '$device' is $([[ "$empty" == true ]] && echo 'empty' || echo 'not empty')"

echo "Unmounting block device '$device' ..."
sudo umount "$dir"
echo "Device '$device' unmounted successfully"
